name: ${project.name}
version: ${project.version}
author: akadia
authors: [ akdaia, sldk ]
main: org.akadia.prometheus.bungeecord.PrometheusBungeeCordExporter
website: akadia.org
description: ${project.description}
